"""Deterministic, idempotent sample data that shows the matching engine at work.

Deliberate cases (see comments): synonyms with no shared words, near misses that the
hard filters must exclude (quantity, budget, lead time, distance, box vs piece),
same-category distractors, competing suppliers, and one supplier fitting several needs.
Coordinates are included so the demo does not depend on a geocoder.
"""

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import Offering, Requirement

CITIES = {
    "London": (51.5074, -0.1278),
    "Manchester": (53.4808, -2.2426),
    "Leeds": (53.8008, -1.5491),
    "Birmingham": (52.4862, -1.8904),
    "Glasgow": (55.8642, -4.2518),
    "Bristol": (51.4545, -2.5879),
    "Liverpool": (53.4084, -2.9916),
    "Sheffield": (53.3811, -1.4701),
    "Newcastle": (54.9783, -1.6178),
    "Rotterdam": (51.9244, 4.4777),
    "Mumbai": (19.0760, 72.8777),
    "Shenzhen": (22.5431, 114.0579),
}

METALS = "Raw Materials & Metals"
ELEC = "Electronics & Electrical"
PACK = "Packaging"
FOOD = "Food & Agriculture"
BUILD = "Construction Materials"
OFFICE = "Office & Consumables"

# client, email, product, category, quantity, unit, budget, city, needed_within_days, notes
REQUIREMENTS = [
    (
        "Northwind Fabrication",
        "buyer@northwind.example.com",
        "MS pipes, 2 inch diameter",
        METALS,
        2000,
        "kg",
        3000,
        "Manchester",
        21,
        "For process water lines",
    ),
    (
        "Harbor Shipyards",
        "procurement@harbor.example.com",
        "Stainless steel sheet 304, 3 mm",
        METALS,
        1,
        "tonne",
        4000,
        "Glasgow",
        30,
        None,
    ),
    (
        "Apex Die Casting",
        "materials@apex.example.com",
        "Aluminium ingots for die casting",
        METALS,
        5,
        "tonne",
        12000,
        "Birmingham",
        30,
        None,
    ),
    (
        "Leeds Railings",
        "orders@leedsrailings.example.com",
        "Steel tubes for handrails",
        METALS,
        800,
        "kg",
        1500,
        "Leeds",
        14,
        "Round section, galvanised preferred",
    ),
    (
        "Precision Fittings",
        "buy@precision.example.com",
        "Brass rods 12 mm",
        METALS,
        300,
        "kg",
        2400,
        "Birmingham",
        20,
        None,
    ),
    (
        "Brightway Retail",
        "sourcing@brightway.example.com",
        "LED bulbs 9W warm white",
        ELEC,
        5000,
        "piece",
        6000,
        "London",
        30,
        "E27 or B22 base",
    ),
    (
        "Volt Contractors",
        "stores@volt.example.com",
        "Copper electrical cable 2.5 sq mm",
        ELEC,
        2000,
        "metre",
        1600,
        "Manchester",
        14,
        "Domestic rewiring jobs",
    ),
    (
        "SolarNest",
        "supply@solarnest.example.com",
        "Solar panels 400W monocrystalline",
        ELEC,
        50,
        "piece",
        7000,
        "Bristol",
        45,
        None,
    ),
    (
        "FactoryTech",
        "maintenance@factorytech.example.com",
        "Industrial circuit breakers MCB 32A",
        ELEC,
        400,
        "piece",
        2000,
        "Sheffield",
        20,
        None,
    ),
    (
        "Newcastle City Council",
        "streets@ncc.example.com",
        "LED street light fixtures 100W",
        ELEC,
        120,
        "piece",
        12000,
        "Newcastle",
        60,
        "Outdoor, IP65 or better",
    ),
    (
        "FreshBox Foods",
        "packaging@freshbox.example.com",
        "Corrugated cardboard boxes for shipping",
        PACK,
        10000,
        "piece",
        5000,
        "Manchester",
        14,
        None,
    ),
    (
        "GreenLeaf Cosmetics",
        "ops@greenleaf.example.com",
        "Biodegradable paper mailer bags",
        PACK,
        5000,
        "piece",
        1500,
        "London",
        21,
        None,
    ),
    (
        "BrewCo",
        "brewery@brewco.example.com",
        "Glass bottles 330ml amber",
        PACK,
        20000,
        "piece",
        5000,
        "Bristol",
        30,
        "For craft beer",
    ),
    (
        "Yorkshire Logistics",
        "depot@yorklog.example.com",
        "Wooden pallets EUR standard",
        PACK,
        300,
        "piece",
        3600,
        "Leeds",
        10,
        None,
    ),
    (
        "SnackCo",
        "buying@snackco.example.com",
        "Food grade plastic containers with lids 500ml",
        PACK,
        10000,
        "piece",
        2500,
        "Liverpool",
        20,
        None,
    ),
    (
        "Spice Route Restaurants",
        "kitchen@spiceroute.example.com",
        "Organic basmati rice",
        FOOD,
        2,
        "tonne",
        5000,
        "London",
        30,
        None,
    ),
    (
        "Bakery Bros",
        "flour@bakerybros.example.com",
        "Wheat flour for bread baking",
        FOOD,
        5000,
        "kg",
        3000,
        "Manchester",
        7,
        None,
    ),
    (
        "Mediterraneo Deli",
        "chef@mediterraneo.example.com",
        "Extra virgin olive oil",
        FOOD,
        1000,
        "litre",
        6000,
        "London",
        30,
        None,
    ),
    (
        "Bean There Coffee",
        "roastery@beanthere.example.com",
        "Arabica coffee beans, green, unroasted",
        FOOD,
        3,
        "tonne",
        18000,
        "Leeds",
        45,
        None,
    ),
    (
        "Juice Junction",
        "orders@juicejunction.example.com",
        "Fresh oranges for juicing",
        FOOD,
        2000,
        "kg",
        2400,
        "Bristol",
        5,
        None,
    ),
    (
        "BuildRight",
        "site@buildright.example.com",
        "Portland cement OPC 53 grade",
        BUILD,
        20,
        "tonne",
        3000,
        "Birmingham",
        14,
        None,
    ),
    (
        "Metro Homes",
        "procure@metrohomes.example.com",
        "TMT steel reinforcement bars 12mm",
        BUILD,
        10,
        "tonne",
        8000,
        "London",
        21,
        None,
    ),
    (
        "Metro Homes",
        "procure@metrohomes.example.com",
        "Ceramic floor tiles 600x600",
        BUILD,
        2000,
        "piece",
        9000,
        "London",
        45,
        None,
    ),
    (
        "GreenBuild Scotland",
        "buyer@greenbuild.example.com",
        "Mineral wool insulation rolls",
        BUILD,
        400,
        "piece",
        8000,
        "Glasgow",
        20,
        "Loft insulation",
    ),
    (
        "Coastal Roads",
        "materials@coastalroads.example.com",
        "Washed river sand for concrete",
        BUILD,
        50,
        "tonne",
        2500,
        "Newcastle",
        10,
        None,
    ),
    (
        "LedgerCo",
        "office@ledgerco.example.com",
        "A4 printer paper 80gsm",
        OFFICE,
        500,
        "box",
        1500,
        "London",
        10,
        None,
    ),
    (
        "Startup Hub",
        "admin@startuphub.example.com",
        "Ergonomic office chairs",
        OFFICE,
        40,
        "piece",
        6000,
        "Manchester",
        21,
        None,
    ),
    (
        "Leeds Schools Trust",
        "supplies@lst.example.com",
        "Blue ballpoint pens",
        OFFICE,
        5000,
        "piece",
        800,
        "Leeds",
        30,
        None,
    ),
    (
        "LedgerCo",
        "office@ledgerco.example.com",
        "Black toner cartridges for HP LaserJet",
        OFFICE,
        60,
        "piece",
        3600,
        "London",
        7,
        None,
    ),
    (
        "Startup Hub",
        "admin@startuphub.example.com",
        "Standing desks, height adjustable",
        OFFICE,
        20,
        "piece",
        8000,
        "Manchester",
        30,
        None,
    ),
]

# supplier, email, product, category, available_qty, unit, unit_price, pricing_notes,
# city, lead_time_days, delivery_scope, notes
OFFERINGS = [
    # "MS pipes 2 inch": synonym (no shared words), a competitor, and three near misses
    (
        "SteelFlow",
        "sales@steelflow.example.com",
        "Mild steel tubes, 50 mm OD",
        METALS,
        5000,
        "kg",
        1.30,
        "5% off above 3 tonnes",
        "Leeds",
        7,
        "regional",
        "Round tube, galvanised option",
    ),
    (
        "Pennine Tube",
        "sales@penninetube.example.com",
        "ERW mild steel pipe 2 inch",
        METALS,
        1.5,
        "tonne",
        1400,
        None,
        "Sheffield",
        10,
        "national",
        None,
    ),
    (
        "Midland Metals",
        "trade@midlandmetals.example.com",
        "MS pipes 2 inch",
        METALS,
        3000,
        "kg",
        3.00,
        None,
        "Birmingham",
        5,
        "national",
        None,
    ),  # far over budget
    (
        "QuickPipe",
        "hello@quickpipe.example.com",
        "Mild steel pipes 2 inch",
        METALS,
        300,
        "kg",
        1.20,
        None,
        "Manchester",
        2,
        "local",
        None,
    ),  # too little stock
    (
        "SlowSteel",
        "orders@slowsteel.example.com",
        "MS pipe 2 inch, black",
        METALS,
        10000,
        "kg",
        1.10,
        None,
        "Liverpool",
        60,
        "regional",
        None,
    ),  # too slow
    (
        "SheetCo",
        "sales@sheetco.example.com",
        "Cold rolled steel sheets 2 mm",
        METALS,
        8000,
        "kg",
        1.10,
        None,
        "Manchester",
        5,
        "local",
        None,
    ),  # distractor
    (
        "EuroAlu",
        "export@euroalu.example.com",
        "Aluminium ingots 99.7% purity",
        METALS,
        20,
        "tonne",
        2200,
        None,
        "Rotterdam",
        21,
        "international",
        None,
    ),
    (
        "Sheffield Stainless",
        "sales@sheffstainless.example.com",
        "SS 304 plates 3 mm",
        METALS,
        2,
        "tonne",
        3200,
        None,
        "Sheffield",
        14,
        "national",
        None,
    ),
    (
        "Brummie Brass",
        "counter@brummiebrass.example.com",
        "Brass round bar 12 mm CZ121",
        METALS,
        1000,
        "kg",
        7.50,
        None,
        "Birmingham",
        3,
        "local",
        None,
    ),
    # LED bulbs: competitors, a distractor, and a box-vs-piece near miss
    (
        "Shenzhen Lumen",
        "export@szlumen.example.com",
        "9 watt LED lamps, 2700K, E27",
        ELEC,
        20000,
        "piece",
        1.05,
        "MOQ 2000",
        "Shenzhen",
        25,
        "international",
        None,
    ),
    (
        "London Lighting",
        "trade@londonlighting.example.com",
        "LED light bulbs 9W B22 warm white",
        ELEC,
        3000,
        "piece",
        1.20,
        None,
        "London",
        5,
        "national",
        None,
    ),
    (
        "StripGlow",
        "sales@stripglow.example.com",
        "LED strip lights RGB 5m",
        ELEC,
        2000,
        "piece",
        1.10,
        None,
        "London",
        3,
        "national",
        None,
    ),  # distractor
    (
        "BoxedBulbs",
        "sales@boxedbulbs.example.com",
        "LED bulbs 9W warm white, box of 10",
        ELEC,
        1000,
        "box",
        9.00,
        None,
        "London",
        3,
        "national",
        None,
    ),  # box != piece
    (
        "Mersey Cables",
        "sales@merseycables.example.com",
        "2.5mm twin and earth copper wire",
        ELEC,
        10000,
        "metre",
        0.65,
        None,
        "Liverpool",
        4,
        "regional",
        None,
    ),
    (
        "Bombay Wires",
        "export@bombaywires.example.com",
        "PVC insulated copper wire 2.5 sqmm",
        ELEC,
        50000,
        "metre",
        0.40,
        None,
        "Mumbai",
        35,
        "international",
        None,
    ),  # too slow
    (
        "SunHarvest EU",
        "b2b@sunharvest.example.com",
        "400 watt mono PERC solar modules",
        ELEC,
        500,
        "piece",
        120,
        None,
        "Rotterdam",
        20,
        "international",
        None,
    ),
    (
        "BudgetSolar",
        "sales@budgetsolar.example.com",
        "Polycrystalline solar panel 330W",
        ELEC,
        200,
        "piece",
        95,
        None,
        "Birmingham",
        10,
        "national",
        None,
    ),
    (
        "Circuit Supply",
        "trade@circuitsupply.example.com",
        "32 amp miniature circuit breaker, C curve",
        ELEC,
        2000,
        "piece",
        4.20,
        None,
        "Birmingham",
        7,
        "national",
        None,
    ),
    (
        "StreetLux",
        "export@streetlux.example.com",
        "100W LED street lamp luminaire IP66",
        ELEC,
        500,
        "piece",
        85,
        None,
        "Shenzhen",
        40,
        "international",
        None,
    ),
    # Cardboard boxes: two competitors (one short on stock) and a distractor
    (
        "NorthPack",
        "sales@northpack.example.com",
        "Double wall carton boxes 400x300x300",
        PACK,
        50000,
        "piece",
        0.42,
        None,
        "Manchester",
        5,
        "local",
        None,
    ),
    (
        "Aire Cartons",
        "orders@airecartons.example.com",
        "Brown shipping cartons, 5-ply corrugated",
        PACK,
        8000,
        "piece",
        0.38,
        None,
        "Leeds",
        7,
        "regional",
        None,
    ),
    (
        "WrapIt",
        "sales@wrapit.example.com",
        "Stretch film pallet wrap rolls",
        PACK,
        5000,
        "piece",
        0.60,
        None,
        "Manchester",
        3,
        "regional",
        None,
    ),  # distractor
    (
        "EcoMail",
        "hello@ecomail.example.com",
        "Compostable kraft paper mailers",
        PACK,
        20000,
        "piece",
        0.25,
        None,
        "London",
        10,
        "local",
        None,
    ),
    (
        "Midlands Glass",
        "sales@midlandsglass.example.com",
        "330 ml amber beer bottles",
        PACK,
        100000,
        "piece",
        0.22,
        None,
        "Birmingham",
        12,
        "national",
        None,
    ),
    (
        "Pallet King",
        "yard@palletking.example.com",
        "Euro pallets 1200x800 heat treated",
        PACK,
        1000,
        "piece",
        11,
        None,
        "Sheffield",
        3,
        "regional",
        None,
    ),
    (
        "DeliPots",
        "sales@delipots.example.com",
        "500ml PP deli pots with lids",
        PACK,
        30000,
        "piece",
        0.20,
        None,
        "Manchester",
        6,
        "regional",
        None,
    ),
    # Rice sold per tonne and per kg (unit conversion)
    (
        "Punjab Grains",
        "export@punjabgrains.example.com",
        "Long grain aromatic basmati rice, certified organic",
        FOOD,
        20,
        "tonne",
        2100,
        None,
        "Mumbai",
        28,
        "international",
        None,
    ),
    (
        "East End Wholesale",
        "trade@eastend.example.com",
        "Basmati rice premium, organic",
        FOOD,
        1500,
        "kg",
        2.40,
        None,
        "London",
        3,
        "local",
        None,
    ),
    (
        "Mersey Mills",
        "orders@merseymills.example.com",
        "Strong white bread flour, 25 kg sacks",
        FOOD,
        20000,
        "kg",
        0.52,
        None,
        "Liverpool",
        2,
        "regional",
        None,
    ),
    (
        "Artisan Mills",
        "sales@artisanmills.example.com",
        "Bread flour T65",
        FOOD,
        10000,
        "kg",
        0.50,
        None,
        "Leeds",
        20,
        "regional",
        None,
    ),  # too slow
    (
        "Olivia Imports",
        "b2b@olivia.example.com",
        "Cold pressed extra virgin olive oil in 5L tins",
        FOOD,
        5000,
        "litre",
        5.20,
        None,
        "Rotterdam",
        14,
        "international",
        None,
    ),
    (
        "SunOil",
        "sales@sunoil.example.com",
        "Refined sunflower oil",
        FOOD,
        8000,
        "litre",
        1.60,
        None,
        "Liverpool",
        5,
        "regional",
        None,
    ),  # distractor
    (
        "Green Bean Traders",
        "trade@greenbean.example.com",
        "Green arabica coffee, washed, 60kg bags",
        FOOD,
        15000,
        "kg",
        5.50,
        None,
        "Rotterdam",
        25,
        "international",
        None,
    ),
    (
        "Citrus Direct",
        "orders@citrusdirect.example.com",
        "Valencia oranges, juicing grade",
        FOOD,
        10000,
        "kg",
        1.00,
        None,
        "Bristol",
        2,
        "local",
        None,
    ),
    # Construction
    (
        "Midland Cement",
        "sales@midlandcement.example.com",
        "OPC 53 cement, 50 kg bags",
        BUILD,
        200,
        "tonne",
        130,
        None,
        "Birmingham",
        3,
        "local",
        None,
    ),
    (
        "SmallBatch Cement",
        "hello@smallbatch.example.com",
        "Ordinary Portland cement",
        BUILD,
        4,
        "tonne",
        120,
        None,
        "Birmingham",
        2,
        "local",
        None,
    ),  # too little stock
    (
        "Yorkshire Rebar",
        "sales@yorkshirerebar.example.com",
        "12 mm rebar, B500B, 12 m lengths",
        BUILD,
        50,
        "tonne",
        720,
        None,
        "Leeds",
        10,
        "national",
        None,
    ),
    (
        "Gujarat Ceramics",
        "export@gujaratceramics.example.com",
        "600x600 vitrified porcelain floor tiles",
        BUILD,
        10000,
        "piece",
        3.80,
        None,
        "Mumbai",
        35,
        "international",
        None,
    ),
    (
        "Tyne Insulation",
        "sales@tyneinsulation.example.com",
        "Glass wool loft insulation roll 100mm",
        BUILD,
        1000,
        "piece",
        17,
        None,
        "Newcastle",
        7,
        "regional",
        None,
    ),
    (
        "Northern Aggregates",
        "quarry@northernagg.example.com",
        "Sharp sand, washed, bulk bags",
        BUILD,
        500,
        "tonne",
        38,
        None,
        "Newcastle",
        2,
        "local",
        None,
    ),
    # Office: paper sold per box and per ream (box != piece)
    (
        "PaperPoint",
        "sales@paperpoint.example.com",
        "Copy paper A4 80 gsm, 5 reams per box",
        OFFICE,
        2000,
        "box",
        2.60,
        None,
        "London",
        2,
        "local",
        None,
    ),
    (
        "ReamSource",
        "orders@reamsource.example.com",
        "A4 printer paper 80gsm ream",
        OFFICE,
        5000,
        "piece",
        0.55,
        None,
        "London",
        2,
        "local",
        None,
    ),  # piece != box
    (
        "SitWell",
        "sales@sitwell.example.com",
        "Mesh task chairs with lumbar support",
        OFFICE,
        200,
        "piece",
        125,
        None,
        "Leeds",
        10,
        "regional",
        None,
    ),
    (
        "PenWorld",
        "export@penworld.example.com",
        "Ballpoint pens blue ink, medium point",
        OFFICE,
        50000,
        "piece",
        0.12,
        None,
        "Shenzhen",
        20,
        "international",
        None,
    ),
    (
        "TonerHouse",
        "sales@tonerhouse.example.com",
        "Compatible HP 26A black toner",
        OFFICE,
        300,
        "piece",
        48,
        None,
        "London",
        1,
        "local",
        None,
    ),
    # One supplier fitting several office needs
    (
        "SitWell",
        "sales@sitwell.example.com",
        "Electric sit-stand desks",
        OFFICE,
        100,
        "piece",
        310,
        None,
        "Leeds",
        14,
        "regional",
        None,
    ),
]


def _coords(city: str) -> dict:
    lat, lon = CITIES[city]
    return {"location": city, "latitude": lat, "longitude": lon}


def seed(db: Session) -> dict:
    """Insert rows that are not there yet (keyed on email + product). Safe to call twice."""
    have_req = set(db.execute(select(Requirement.contact_email, Requirement.product_requirement)))
    have_off = set(db.execute(select(Offering.contact_email, Offering.product_offered)))
    new_req = [
        Requirement(
            client_name=name,
            contact_email=email,
            product_requirement=product,
            category=cat,
            quantity=qty,
            unit=unit,
            budget=budget,
            needed_within_days=days,
            notes=notes,
            **_coords(city),
        )
        for name, email, product, cat, qty, unit, budget, city, days, notes in REQUIREMENTS
        if (email, product) not in have_req
    ]
    new_off = [
        Offering(
            supplier_name=name,
            contact_email=email,
            product_offered=product,
            category=cat,
            available_quantity=qty,
            unit=unit,
            unit_price=price,
            pricing_notes=pricing,
            lead_time_days=lead,
            delivery_scope=scope,
            notes=notes,
            **_coords(city),
        )
        for name, email, product, cat, qty, unit, price, pricing, city, lead, scope, notes in OFFERINGS
        if (email, product) not in have_off
    ]
    db.add_all(new_req + new_off)
    db.commit()
    return {"requirements_created": len(new_req), "offerings_created": len(new_off)}
